<?php 

$resp = $this->respuesta;

?>

<script type="text/javascript">
    var res = <?php echo $resp; ?>

    var msg = Ext.create('Ext.window.MessageBox');
    console.log(res);
    if (res.code == 200){
        
        msg.alert('Listo', res.message,window.location = '/client');

    }else{
/*       msg.show({
                title : 'Error',
                msg : res.message,                
                
                fn : function(buttonValue, inputText, showConfig){
                    window.location = '/client'
                },
                iconCls : 'fa fa-times'
            });
*/
       msg.alert('Listo', res.message,window.location = '/client');
    }
    
</script>