<script type="text/javascript">
       
var datos = <?php echo $this->data; ?>;      
Ext.onReady(function() {

    var forn = Ext.create('Ext.form.Panel',{
        title: datos.name,
        iconCls: 'fa fa-user',
        width: 600,
        bodyPadding: 12,
        items: [{
            xtype: 'textfield',
            fieldLabel: 'Nombre',
            name: 'name',
            value: datos['name'],
            allowBlank: false,
        },{
            xtype: 'textfield',
            fieldLabel: 'Identificacion',
            name: 'identification'
        },{
            xtype: 'textfield',
            fieldLabel: 'Direccion',
            name: 'address'
        },{
            xtype: 'textfield',
            fieldLabel: 'Ciudad',
            name: 'city'
        },{
            xtype: 'textfield',
            fieldLabel: 'Correo electronico',
            name: 'email'
        },{
            xtype: 'textfield',
            fieldLabel: 'Telefono1',
            name: 'phonePrimary'
        },{
            xtype: 'textfield',
            fieldLabel: 'Telefono2',
            name: 'phoneSecondary'
        },{
            xtype: 'textfield',
            fieldLabel: 'Fax',
            name: 'fax'
        },{
            xtype: 'textfield',
            fieldLabel: 'Celular',
            name: 'mobile'
        },{
           xtype: 'combobox',
           fieldLabel: 'Lista de precoi',
           name: 'priceList',
           store: Ext.create('Ext.data.Store', {
                    fields: ['name'],
                    data: [{ 
                       'name': 'General'
                    },{
                       'name': 'Ninguna'
                    }]
                 }),
           valueField: 'name',
           displayField: 'name'
        },{
            xtype: 'combobox',
            fieldLabel: 'Vendedor',
            name: 'seller',
            store: Ext.create('Ext.data.Store', {
                fields: ['name'],
                data: [{ 
                   'name': 'Seleccione'
                },{
                   'name': 'Ninguna'
                }]
             }),
        },{
            xtype: 'checkboxfield',
            fieldLabel: 'Cliente',
            inputValue: '1',
            name: 'type'
        },{
            xtype: 'checkboxfield',
            fieldLabel: 'Proveedor',
            inputValue: '1',
            name: 'type'
        },{
            xtype: 'textarea',
            fieldLabel: 'Observaciones',
            name: 'observations'
        }/*,{
            xtype: 'checkboxfield',
            fieldLabel: 'Incluir estado de cuenta',
            inputValue: '1',
        }*/],
        buttons: [{
        	text: 'Limpiar',
        	handler: function(){
        		this.up('form').getForm().reset();
        	}
        },{
        	text: 'Enviar',
        	formBind: true,
        	handler: function(){
        		var form = this.up('form').getForm();
        		forn.getForm().submit({
        			method: 'POST',
        			standardSubmit:true,
		    		url: 'http://localhost:8080/client/store',
		    		
		    		success: function(form, action){
						console.log("listo");
		    				Ext.Msg.alert('Listo CTM!', action.result.msg);
		    				
		    			},
		    			failure: function(form, action){
		    				console.log("fallo esta mierda"+action.result.msg);

		    				Ext.Msg.alert('csm', action.result.msg);
		    			}
        		});
        		if(form.isValid()){
        			form.submit({
        				method: 'POST',
		    			url: 'http://localhost:8080/client/store',
		    			success: function(form, action){
		    				Ext.Msg.alert('Listo CTM!', action.result.msg);
		    				console.log("listo");
		    			},
		    			failure: function(form, action){
		    				Ext.Msg.alert('csm', action.result.msg);
		    			}
		    		});
        		}
        	}
        }],
        renderTo: Ext.getBody()
    });
    /*Ext.define('MyCont',{
    	extend: 'Ext.app.ViewController',

    	onSubmit: function() {
    		var form = this.getView();

    		form.submit({
    			url: 'url',
    			success: function(){
    				Ext.Msg.alert('Listo CTM!');
    			}
    		});
    	}
    });*/
});

</script>