<script type="text/javascript">
       
var datos = <?php echo $this->data; ?>; 
Ext.require('Ext.panel.Panel');     
Ext.onReady(function() {

    Ext.onReady(function(){
    var data = datos;

    new Ext.panel.Panel({
        width: 300,
        margin: 15,
        bodyPadding: 5,
        title: 'Basic Template',
        tpl: [
            '<p>Nombre: {name}</p>',
            '<p>Identificación: {identification}</p>',
            '<p>Direccion: {address.address} {address.city}</p>',
        ],
        tbar: [{
            text: 'Apply Template',
            handler: function() {
                this.up('panel').update(data);
            }
        }],
        html: '<p><i>Apply the template to see results here</i></p>',
        renderTo: Ext.getBody()
    });

    /*new Ext.panel.Panel({
        width: 300,
        renderTo: 'xtemplate-example',
        margin: 15,
        bodyPadding: 5,
        title: 'XTemplate',
        tpl: [
            '<p>Name: {name}</p>',
            '<p>Company: {company}</p>',
            '<p>Location: {city}, {state}</p>',
            '<p>Kids: ',
            '<tpl for="kids">',
                '<tpl if="age &gt; 1"><p>{#}. {parent.name}\'s kid - {name}</p></tpl>',
            '</tpl></p>'
        ],
        tbar: [{
            text: 'Apply Template',
            handler: function() {
                this.up('panel').update(data);
            }
        }],
        html: '<p><i>Apply the template to see results here</i></p>'
    });*/
});

});

</script>