<script type="text/javascript">
       
var datos = <?php echo $this->data; ?>; 
Ext.require('Ext.panel.Panel');     
Ext.onReady(function() {

    Ext.onReady(function(){
    var data = datos;

    new Ext.panel.Panel({
        width: 800,
        bodyPadding: 5,
        title: datos.name,
        iconCls: 'fa fa-user',
        tpl: [
            '<p>Nombre: {name}</p>',
            '<p>Identificación: {identification}</p>',
            '<p>Direccion: {address.address} {address.city}</p>',
            '<p>Teléfono: {phonePrimary}</p>',
            '<p>Teléfono 2: {phoneSecondary}</p>',
            '<p>Celular: {mobile}</p>',
            '<p>Correo electrónico: {email}</p>',
            '<p>Observaciones: {observations}</p>',
        ],
        dockedItems: [{
            xtype: 'toolbar',
            items: [{
                itemId: 'delete',
                text: 'Delete',
                iconCls: 'text-danger fa fa-times',
                handler: function(){
                    window.location = '/client/delete/id/'+datos.id;
                }
            }, '-', {
                itemId: 'edit',
                text: 'Editar',
                iconCls: 'fa fa-pencil',
                handler: function(){
                    window.location = '/client/edit/id/'+datos.id;
                }
            }]
        }],
        html: [
'<dl class="row">',
'  <dt class="col-sm-3">Nombre</dt>',
  '<dd class="col-sm-9">'+datos.name+'</dd>',
  '<dt class="col-sm-3">Euismod</dt>',
  '<dd class="col-sm-9">'+datos.identification+'</dd>',
  '<dt class="col-sm-3">Direccion</dt>',
  '<dd class="col-sm-9"><p>'+datos.address.address+'</p><p>'+ datos.address.city+'</p></dd>',
  '<dt class="col-sm-3">Teléfono</dt>',
 '<dd class="col-sm-9">'+datos.phonePrimary+'</dd>',
  '<dt class="col-sm-3">Teléfono 2</dt>',
  '<dd class="col-sm-9">'+datos.phoneSecondary+'</dd>',
  '<dt class="col-sm-3">Celular</dt>',
  '<dd class="col-sm-9">'+datos.mobile+'</dd>',
  '<dt class="col-sm-3">Correo electrónico</dt>',
  '<dd class="col-sm-9">'+datos.email+'</dd>',
  '<dt class="col-sm-3">Observaciones</dt>',
  '<dd class="col-sm-9">'+datos.observations+'</dl>',
/*            '<p>Nombre: '+datos.name+'</p>',
            '<p>Identificación: '+datos.identification+'</p>',
            '<p>Direccion: '+datos.address.address+', '+ datos.address.city+'</p>',
            '<p>Teléfono: '+datos.phonePrimary+'</p>',
            '<p>Teléfono 2: '+datos.phoneSecondary+'</p>',
            '<p>Celular: '+datos.mobile+'</p>',
            '<p>Correo electrónico: '+datos.email+'</p>',
            '<p>Observaciones: '+datos.observations+'</p>',*/
        ],
        renderTo: Ext.getBody()
    });

});

});

</script>

