<script type="text/javascript">
	var res = <?php echo $this->resp; ?>

    var msg = Ext.create('Ext.window.MessageBox');
    console.log(res);
    if (res.code == 400){
        msg.alert(res.error, res.message,window.location = '/client/add');
        

    }else{

    msg.alert('Listo, Nuevo contacto agregado', res.message,window.location = '/client/show/id/'+res.id);
       
    }
</script>



