<?php $datos = $this->datos; ?>

<script type="text/javascript">

	var res = <?php echo $datos; ?>

    var msg = Ext.create('Ext.window.MessageBox');
    console.log(res);
    if (res.code == 2013){
        msg.alert(res.error, res.message,window.location = '/client');
        

    }else{
       msg.show({
            title : 'Listo, ya se ha editado',
            msg : 'Todo ha salido bien',                
            
            fn : function(buttonValue, inputText, showConfig){
                window.location = '/client'
            },
            iconCls : 'fa fa-check'
        });
       
    }
</script>