<?php $datos = $this->datos; ?>

<script type="text/javascript">

	var res = <?php echo $datos; ?>;

    var msg = Ext.create('Ext.window.MessageBox');
    console.log(res);
    if (res.code == 2013){
        msg.alert(res.error, res.message,window.location = '/client');
        

    }else{

       msg.alert('Listo, ya se ha actualizado', 'Se actualizo: '+res.name,window.location = '/client/show/id/'+res.id);
    }
</script>