<div class="container">
      <div class="header clearfix">
        <nav>
          <ul class="nav nav-pills float-right">
            <li class="nav-item">
              <a class="nav-link active" href="#">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/client">Contactos</a>
            </li>
          </ul>
        </nav>
        <h3 class="text-muted">Mis Contactos</h3>
      </div>

      <div class="jumbotron">
        <h1 class="display-3">Mis Contactos</h1>
        <p class="lead">Hola, bienvenidos a mi página de contactos, aqui puedes crear, editar, borrar y listas los contactos sin problema alguno, no esperes mas, empieza ahora!.</p>
        <p><a class="btn btn-lg btn-success" href="/client" role="button">Ver los Contactos</a></p>
      </div>
</div>