<div class="jumbotron">
	<h2 class="display-3">Acerca de mi Aplicacion</h2>
	<hr>
	<p class="lead">Aplicación para conectar con <a target="_blank" href="https://www.alegra.com">Alegra</a> y gestionar <a href="/">Mis Contactos</a> con el uso de Alegra API</p>
	<p>El Codigo fuente esta disponible en <a target="_blank" href="https://github.com/vicmans/contactos"><i class="fa fa-github"></i> github.com/vicmans/contactos</a></p>
	<p>Cualquier duda, sugerencia o comentario escribe a <a href="mailto:vsanchezl94@gmail.com">vsanchezl94@gmail.com</a></p>
	<p>Saludos!</p>
</div>