<!doctype html>
<html lang="es">
	<head>
		<meta charset="utf-8">
		
		<?php echo $this->headMeta(); ?>
		<?php echo $this->headTitle('Mis Contactos'); ?>
		<?php echo $this->headLink()->appendStylesheet('/css/styles.css'); ?>
		<!-- Le styles --> 
<!-- 
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
 -->
      <link href="https://cdnjs.cloudflare.com/ajax/libs/extjs/6.0.0/classic/theme-crisp/resources/theme-crisp-all.css" rel="stylesheet" />
      
      <script src="https://use.fontawesome.com/f1559b8ac6.js"></script>
      <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/extjs/6.0.0/ext-all.js"></script>

      <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
	<?php echo $this->headScript(); ?>
	</head>
	<body>

	<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Mis Contactos</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        
        <li><a href="/client">Contactos</a></li>
        <li><a href="/client/clients">Clientes</a></li>
		<li><a href="/client/providers">Proveedores</a></li>
       
      </ul>
      <form class="navbar-form navbar-left" action="/client/buscar" method="post">
        <div class="form-group">
          <input type="text" class="form-control" name="busca" placeholder="Busca por nombre">
        </div>
        <button type="submit" class="btn btn-default">Buscar</button>
      </form>
      
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<div class="container">
		<div id="content">
			<?php echo $this->layout()->content; ?>
			<?php echo $this->inlineScript(); ?>
		</div>


		<footer class="footer">
			&copy; 2017, Victor Sanchez, Zend Framework <?php echo Zend_Version::VERSION; ?>
		</footer>
</div>
	</body>
</html>